### ISSUE TITLE
Skip images without annotations

### ISSUE THREAD

**Issue by mmoollllee** [kadapallaNithin/yolo2labelme#1]
For images without a corresponding .txt file, notice should be printed but no error be throun, no?

Would be nice :)

```
Traceback (most recent call last):
  File "/Users/mg/dev/yolo-nas-object-blurring/venv/bin/yolo2labelme", line 8, in <module>
    sys.exit(main())
  File "/Users/mg/dev/yolo-nas-object-blurring/venv/lib/python3.9/site-packages/yolo2labelme.py", line 94, in main
    yolo2labelme(args.data, args.out)
  File "/Users/mg/dev/yolo-nas-object-blurring/venv/lib/python3.9/site-packages/yolo2labelme.py", line 85, in yolo2labelme
    yolo2labelme_single(txt_file, img_file, class_labels, out_dir)
  File "/Users/mg/dev/yolo-nas-object-blurring/venv/lib/python3.9/site-packages/yolo2labelme.py", line 54, in yolo2labelme_single
    result['shapes'] = get_shapes(txt_path, img.width, img.height, class_labels)
  File "/Users/mg/dev/yolo-nas-object-blurring/venv/lib/python3.9/site-packages/yolo2labelme.py", line 26, in get_shapes
    shapes = open(txt_path).read().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: './test/labels/20230731_152008.txt'
```

**Comment by kadapallaNithin** [comment]
Added requested feature. Go through the README and let me know if it works.
